### ISSUE TITLE
请问单机两卡（A40）训练stage one ,都需要修改哪些参数呢？

### ISSUE THREAD

**Issue by Sarah-air** [zhengchen1999/HI-Diff#19]
命令行改为python -m torch.distributed.launch --nproc_per_node=2 --master_port=21 train.py -opt options/train/GoPro_S1.yml --launcher pytorch为什么报错啊？
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 223240) of binary: /root/anaconda3/envs/hi_diff/bin/python

**Comment by zhengchen1999** [comment]
https://github.com/zhengchen1999/HI-Diff/blob/main/options/train/GoPro_S1.yml#L22

batch_size_per_gpu: 32 （满足总batch=64）

**Comment by Sarah-air** [comment]
> https://github.com/zhengchen1999/HI-Diff/blob/main/options/train/GoPro_S1.yml#L22
> 
> batch_size_per_gpu: 32 （满足总batch=64）

好的，多谢

**Comment by Sarahsus** [comment]
> https://github.com/zhengchen1999/HI-Diff/blob/main/options/train/GoPro_S1.yml#L22
> 
> batch_size_per_gpu: 32 （满足总batch=64）

请问我用单个卡可以训，单卡： python -m torch.distributed.launch --nproc_per_node=1 --master_port=1 train.py -opt options/train/GoPro_S1.yml --launcher pytorch
为什么双卡就报错了，网上也没找到解决办法，请问可能是什么原因呢？
双卡命令：python -m torch.distributed.launch --nproc_per_node=2 --master_port=21 train.py -opt options/train/GoPro_S1.yml --launcher pytorch；
报错：
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 628290 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 628289) of binary: /root/anaconda3/envs/hi_diff/bin/python
Traceback (most recent call last):
  File "/root/anaconda3/envs/hi_diff/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/hi_diff/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/envs/hi_diff/lib/python3.9/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/root/anaconda3/envs/hi_diff/lib/python3.9/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/root/anaconda3/envs/hi_diff/lib/python3.9/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/root/anaconda3/envs/hi_diff/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/root/anaconda3/envs/hi_diff/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/anaconda3/envs/hi_diff/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-15_09:38:33
  host      : iZ1pp06qu51okcqpofidokZ
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 628289)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
